export default {
    "Title": "عنوان",
    "Add {{title}}" : "افزودن {{title}}",
    "Search {{title}}" : "جستجو در {{title}} ها",
    "All {{title}}" : "{{title}} ها",
    "Edit {{title}}" : "ویرایش {{title}}",
    "Menu" : "منو",
    "Export" : "خروجی اکسل",
    "Edit" : "ویرایش",
    "Delete" : "حذف",
    "Search" : "جستجو",
    "User" : "کاربر",
    "Position" : "موقعیت",
    "Url" : "آدرس",
    "Status" : "وضعیت",
    "Date" : "تاریخ",
    "Actions" : "عملیات",
    "Cms" : "محتوی",
    "Home" : "خانه",
    "Save" : "ذخیره",
    "Reset" : "بازیابی فرم",
    "Parent Menu" : "منوی اصلی",
    "Icon" : "آیکون",
    "Svg" : "Svg",
    "Enable" : "فعال",
    "Disable" : "غیرفعال",
    "Next" : "بعدی",
    "Previous" : "قبلی",
    "Showing" : "نمایش",
    "of" : "از",
    "Select" : "انتخاب کنید",
    "Just put svg paths" : "فقط تگ path را قرار دهید",
    "Top" : "بالا",
    "Right" : "راست",
    "Bottom" : "پایین",
    "Left" : "چپ",
    "Search..." : "جستجو ...",
    "Dashboard" : "داشبورد",
    "Setting" : "تنظیمات",
    "Media" : "مدیا",
    "Group" : "گروه",
    "Yes, I'm sure" : "بله، مطمئن هستم",
    "No, cancel" : "نه، لغو",
    "Are you sure you want to delete this ?" : "آیا از حذف این مورد اطمینان دارید ؟",
    
}