export default {
    "Title": "عنوان",
    "Add {{title}}" : "افزودن {{title}}",
    "Search {{title}}" : "جستجو در {{title}} ها",
    "All {{title}}" : "{{title}} ها",
    "Edit {{title}}" : "ویرایش {{title}}",
    "Menu" : "منو",
    "Export" : "خروجی اکسل",
    "Edit" : "ویرایش",
    "Delete" : "حذف",
    "Search" : "جستجو",
    "User" : "کاربر",
    "Position" : "موقعیت",
    "Url" : "آدرس",
    "Status" : "وضعیت",
    "Date" : "تاریخ",
    "Actions" : "عملیات",
    "Cms" : "محتوی",
    "Home" : "خانه",
    "Save" : "ذخیره",
    "Reset" : "بازیابی فرم",
    "Parent Menu" : "منوی اصلی",
    "Icon" : "آیکون",
    "Svg" : "Svg",
    "Enable" : "فعال",
    "Disable" : "غیرفعال",
    "Next" : "بعدی",
    "Previous" : "قبلی",
    "Showing" : "نمایش",
    "of" : "از",
    "Select" : "انتخاب کنید",
    "Just put svg paths" : "فقط تگ path را قرار دهید",
    "Top" : "بالا",
    "Right" : "راست",
    "Bottom" : "پایین",
    "Left" : "چپ",
    "Search..." : "جستجو ...",
    "Dashboard" : "داشبورد",
    "Setting" : "تنظیمات",
    "Media" : "مدیا",
    "Group" : "گروه",
    "Yes, I'm sure" : "بله، مطمئن هستم",
    "No, cancel" : "نه، لغو",
    "Are you sure you want to delete this ?" : "آیا از حذف این مورد اطمینان دارید ؟",
    "404 Page not found" : "404 صفحه مورد نظر یافت نشد",
    "Oops! Looks like you followed a bad link. If you think this is a problem with us, please tell us." : "صفحه ای که دنبال آن میگردید پیدا نشد.",
    "Go back home" : "بازگشت به خانه",
    "Your email" : "ایمیل",
    "Your password" : "رمز ورود",
    "Remember me" : "یاد آوری",
    "Login to your account" : "ورود",
    "Lost Password?" : "رمز عبور خود را گم کرده اید ؟",
    "Login" : "ورود",
    "Post" : "پست",
    "Page" : "صفحه",
    "Comment" : "نظرات",
    "Create" : "ایجاد",
    "Update" : "بروزرسانی",
    "View" : "نمایش",
    "Name" : "نام",
    "Email" : "ایمیل",
    "Password" : "رمز",
    "Re-Password" : "رمز مجدد",
    "Is Admin" : "ادمین باشد",
    "Is Main" : "اصلی باشد",
    "Main" : "اصلی",
    "Not main" : "اصلی نباشد",
    "Admin" : "مدیر",
    "All" : "همه",
    "Message" : "پیام ها",
    "Shop" : "فروش",
    "Variant" : "معیار قیمت",
    "Price" : "قیمت ها",
    "Category" : "دسته بندی",
    "Product" : "محصول",
    "Parameter" : "پارامتر ها",
    "Gallery" : "گالری تصاویر",
    "Brand" : "برند",
    "Warranty" : "گارانتی",
    "Settings page" : "تنظیمات",
    "Has Comment" : "نظرات",
    "Has" : "دارد",
    "Doesn't have" : "ندارد",
    "Attachments" : "فایل ها",
    "Attachment" : "فایل",
    "Module" : "ماژول",
    "Add Attachment to {{title}}" : "افزودن فایل به {{title}}",
    "Files" : "فایل ها",
    "File" : "فایل",
    "Description" : "توضیحات",
    "System" : "سیستمی",
    "Log" : "لاگ",
    "Task" : "وظایف",
    "Post Type" : "نوع پست",
    "Order" : "سفارش",
    "Action" : "عمل",
    "create" : "ایجاد",
    "update" : "ویرایش",
    "Short Content" : "متن کوتاه",
    "Content" : "متن",
    "Priority" : "ترتیب",
    "Type" : "نوع",
    "Parent Category" : "دسته بندی اصلی",
    "shop/settings" : "فروش / تنظیمات",
    "shop/warranties" : "فروش / گارانتی",
    "Change Password" : "تغییر رمز عبور",
    "Change {{title}} Password" : "تغییر رمز عبور {{title}}",
    "Toggle dark mode" : "تغییر حالت قالب",
    "Profile" : "مشخضات کاربری",
    "Sign out" : "خروج",
    "Settings" : "تنظیمات",
    "Apps" : "کاربری",
    "Sales" : "فروش",
    "Users" : "کاربران",
    "Inbox" : "پیام ها",
    "Products" : "محصولات",
    "Pricing" : "قیمت گذاری",
    "Billing" : "مالی",
    "Logout" : "خروج",
}